# Generated by Django 2.1 on 2018-08-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Html',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=49)),
                ('filename', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=4)),
                ('title', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
    ]
