# Generated by Django 2.1 on 2018-08-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='html',
            old_name='hash',
            new_name='multihash',
        ),
    ]
