# Generated by Django 2.1 on 2018-08-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0004_auto_20180810_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multihash', models.CharField(max_length=49)),
            ],
        ),
    ]
