version: "3"

services:
  ipfs:
    image: ipfs/go-ipfs
    command: ['daemon', '--migrate=true', '--enable-gc']
    ports:
      # Swarm TCP
      - "4001:4001"
      # HTTP API
      - "5001:5001"
      # Gateway
      - "8080:8080"

  db:
    build: ./db

  crawler:
    build:
      context: .
      dockerfile: ./crawler/Dockerfile
    depends_on:
      - ipfs
      - db
    volumes:
      - /data
    stop_signal: SIGINT

  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    depends_on:
      - db
    ports:
      - "9000:9000"
    stop_signal: SIGINT
