version: "3"

services:
  ipfs:
    image: ipfs/go-ipfs

  db:
    build: ./db

  crawler:
    build:
      context: .
      dockerfile: ./crawler/Dockerfile
    depends_on:
      - ipfs
      - db

  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    depends_on:
      - db
